version: '3'
services:
  web_t10:
    image: java_springv1_t10
    build: .
    ports:
      - "8100:8100"
    volumes:
      - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/t10_team10/volumes
